version: "3.1"

services:

    postgres:
        image: postgres:14
        env_file: .env
        restart: always
        volumes:
        - postgres:/var/lib/postgresql/data
        ports:
        - ${POSTGRES_PORT}:5432

    backend:
        build: 
            dockerfile: ./backend/Orders.WebApi/Dockerfile
        env_file: .env
        ports:
        - ${BACKEND_HTTP_PORT}:80
        - ${BACKEND_HTTPS_PORT}:443
        environment:
            POSTGRES_HOST: postgres
volumes:
    postgres: